board_games/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('boardgames.urls')),
]
# Handle 404 urls
handler404 = 'boardgames.views.error_404_view'

boardgames/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name= 'boardgames'
urlpatterns= [
    #Home page
    path('', views.index, name='index'),
    path('games/', views.games, name='games'),
    #Page for adding a new game
    path('new_game/', views.new_game, name='new_game'),
    #Page for a single game
    path('games/<int:game_id>/', views.game, name='game'),
    #Page for loaning a game
    path('new_loan/<int:game_id>/', views.new_loan, name='new_loan'),
    #Page for editing a loan
    path('edit_loan/<int:loan_id>/', views.edit_loan, name='edit_loan'),
    url(r'^delete/(?P<loan>[0-9]+)/$', views.loan_delete, name='loan_delete'),
    #Page for editing a game
    path('edit_game/<int:game_id>/', views.edit_game, name='edit_game'),
    
]

users/urls.py
from django.urls import path, include
from django.urls import URLPattern
from . import views

app_name= 'users'
urlpatterns= [
    #Include default auth urls.
path('', include('django.contrib.auth.urls')), 
path('register/', views.register, name='register'),
]

boardgames/models.py
from django.db import models


class Game(models.Model):
    """The Board Game"""
    text = models.CharField(max_length=250)
    description = models.TextField(default="Describe your game")
    owner = models.CharField(default="Owner", max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """The string representation of the model"""
        return self.text


class Loan(models.Model):
    # Loaning the game, loaner writes their name and ticks a box
    loaner = models.CharField(max_length=50, default="Write your name")
    on_loan = models.BooleanField(default=False)
    date_modified = models.DateTimeField(auto_now_add=True)

    # delete description when game is deleted
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        # return name of the loaner
        return self.loaner[:50]

users/models.py
from django.db import models

# Create your models here.

boardgames/forms.py
from django import forms
from django.db.models import fields

from .models import Game, Loan

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['text', 'description', 'owner']
        labels = {'text': '', 'description': '', 'owner': ''}

class LoanForm(forms.ModelForm):
    class Meta:
        model=Loan
        fields= ['loaner', 'on_loan']

boardgames/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Game, Loan
from .forms import GameForm, LoanForm

# Create your views here.


def index(request):
    """The home page for Board Game Website"""
    return render(request, 'boardgames/index.html')


@login_required
def games(request):
    """The page for All Board Games"""
    games = Game.objects.order_by('-date_added')
    context = {'games': games}
    return render(request, 'boardgames/games.html', context)


@login_required
def new_game(request):
    """Add a new game."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = GameForm()
    else:
        # POST data submitted; process data.
        form = GameForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boardgames:games')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'boardgames/new_game.html', context)


@login_required
def new_loan(request, game_id):
    game = Game.objects.get(id=game_id)
    """Loan a game."""
    if request.method != 'POST':
        # No data submittes; create a blank form.
        form = LoanForm()
    else:
        # POST data submitted; process data.
        form = LoanForm(data=request.POST)
        if form.is_valid():
            new_loan = form.save(commit=False)
            new_loan.game = game
            new_loan.save()
            return redirect('boardgames:game', game_id=game_id)

    # Display a blank or invalid form.
    context = {'game': game, 'form': form}
    return render(request, 'boardgames/new_loan.html', context)


@login_required
def game(request, game_id):
    """Show a single game and it's availability"""
    game = Game.objects.get(id=game_id)
    loans = game.loan_set.order_by('loaner')
    context = {'game': game, 'loans': loans}
    return render(request, 'boardgames/game.html', context)


@login_required
def edit_loan(request, loan_id):
    """Edit an existing loan."""
    loan = Loan.objects.get(id=loan_id)
    game = loan.game

    if request.method != 'POST':
        # Initial request; pre-fill form with the current loan.
        form = LoanForm(instance=loan)
    else:
        # POST data submitted; Process data
        form = LoanForm(instance=loan, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boardgames:game', game_id=game.id)

    context = {'loan': loan, 'game': game, 'form': form}
    return render(request, 'boardgames/edit_loan.html', context)


@login_required
def loan_delete(request, loan):
    loan = Loan.objects.get(id=loan)  # Get your current loan

    if request.method == 'POST':         # If method is POST,
        loan.delete()                     # delete the loan.
        # Finally, redirect to the homepage.
        return redirect('/games')

    return render(request, 'boardgames/games', {'loan': loan})

@login_required
def edit_game(request, game_id):
    """Edit an existing game."""
    game = Game.objects.get(id=game_id)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current game.
        form = GameForm(instance=game)
    else:
        # POST data submitted; Process data
        form = GameForm(instance=game, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boardgames:game', game_id=game.id)

    context = {'game': game, 'form': form}
    return render(request, 'boardgames/edit_game.html', context)

# Directs to 404 page when not found a page
def error_404_view(request, exception):
    return render(request, 'boardgames/404.html')

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

#Register a new user
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # 1 blanky boi
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():            
            new_user = form.save()
            #Log the user into the site and onto the home page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('boardgames:index'))

    context = {'form': form}
    return render(request, 'registration/register.html', context)

boardgames/templates/boardgames/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Board Games</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
  
      <a class="navbar-brand" href="{% url 'boardgames:index'%}">
          Board Games</a>
  
      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'boardgames:games'%}">
                    Games</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
              </ul>
            </div>
        
          </nav>

          <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
              {% block page_header %}{% endblock page_header %}
            </div>
            <div>
              {% block content %}{% endblock content %}
            </div>
          </main>
        
        </body>
        
        </html>

boardgames/templates/boardgames/edit_game.html
{% extends "boardgames/base.html" %}

{% block content %}

    <p><a href="{% url 'boardgames:game' game.id %}">{{ game }}</a></p>

    <p>Edit game:</p>

    <form action="{% url 'boardgames:edit_game' game.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

    {% endblock content %}

boardgames/templates/boardgames/edit_loan.html
{% extends "boardgames/base.html" %}

{% block content %}

    <p><a href="{% url 'boardgames:game' game.id %}">{{ game }}</a></p>

    <p>Edit loan:</p>

    <form action="{% url 'boardgames:edit_loan' loan.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
    <form action="{% url 'boardgames:loan_delete' loan.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Return game">
    </form>

    {% endblock content %}

boardgames/templates/boardgames/game.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <h3>{{ game }}</h3>
{% endblock page_header %}

{% block content %}

<p><a href="{% url 'boardgames:edit_game' game.id %}">
  Edit game</a></p>
  
<p>Description: {{ game.description }}</p>
<p>Owner: {{ game.owner }}</p>

  {% for loan in loans %}
    <div class="card mb-3">
      <h4 class="card-header">
        <small><a href="{% url 'boardgames:edit_loan' loan.id %}">
              Edit loan</a></small>
        </h4>
        <div class="card-body">
          <p>{{ loan.loaner }} {% if loan.on_loan == True %} has loaned this game 
            {{ loan.date_modified|date:'M d, Y H:i' }}.
        </div>
      </div>
        
{%endif%}

{%empty%}
  <div class="card mb-3">
    <h4 class="card-header">
      <small><a href="{% url 'boardgames:new_loan' game.id %}">Loan this game</a></small>
      </h4>
      <div class="card-body">
        <p>This game is available.
      </div>
    </div>

{%endfor%}

{%endblock content%}

boardgames/templates/boardgames/games.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <h1>Board Games</h1>
{% endblock page_header %}

{% block content %}
<h2>All Board Games</h2>
<ul>
    {% for game in games %}
        <li><h3>
            <a href="{% url 'boardgames:game' game.id %}">{{ game }}</a>
        </h3></li>
    {% empty %}
        <li><h3>No games have been added yet.</h3></li>
    {% endfor %}
    </ul>

    <h3><a href="{% url 'boardgames:new_game' %}">Add a new game</a></h3>
    
{% endblock content %}

boardgames/templates/boardgames/index.html
{% extends "boardgames/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Borrow board games from others.</h1>

    <p class="lead">List all the board games you own and borrow games from others. Keep track of who
        has your game and find out which games are available.
    </p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

boardgames/templates/boardgames/new_game.html
{% extends "boardgames/base.html" %}

{% block content %}
    <p>Add a new game:</p>

    <form action="{% url 'boardgames:new_game' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add game</button>
    </form>

{% endblock content %}

boardgames/templates/boardgames/new_loan.html
{% extends "boardgames/base.html" %}
{% block content %}

<p>Loan <a href="{% url 'boardgames:game' game.id %}">{{game}}</a>:</p>
<form action="{% url 'boardgames:new_loan' game.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Loan</button>
</form>

{% endblock content %}

users/templates/logged_out.html
{% extends "boardgames/base.html" %}

{% block content %}

    <p>You have been logged out. Thank you for visiting!</p>

{% endblock content %

users/templates/register.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <form method='post' action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Register</button>
    <input type='hidden' name='next' value="{% url 'boardgames:index' %}" />
  </form>
{% endblock content %